name: smart_habit_health_companion
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.2.8+4

  # Firebase
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_messaging: ^15.2.10

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

  # Local notifications & timezone
  flutter_local_notifications: ^18.0.1
  flutter_native_timezone: ^2.0.0
  timezone: ^0.9.3

  # UI
  cupertino_icons: ^1.0.8
  sqflite_common_ffi: ^2.3.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  analyzer: ^6.4.1
